### PR TITLE
Delete stale pod IPs

### LINKED ISSUE #167: Prune Prometheus metrics for defunct peer pod IPs after rolling updates
## Problem

After a DaemonSet rolling update (e.g. upgrading from v3.10.3 to v3.11.0), goldpinger retains Prometheus histogram/counter series for **old pod IPs that no longer exist**. These stale series persist for the entire lifetime of the surviving pods and skew percentile calculations (P95/P99), making it appear that there's a latency regression or connectivity issue when in reality the cluster is healthy.

This is distinct from #87 (NotReady nodes) — here all nodes are healthy, but the metric label sets contain pod IPs from pods that were replaced during the rollout.

## Observed behavior

After upgrading goldpinger on a 6-node IPv6 k8s cluster, the `/metrics` endpoint on a surviving pod shows series for both the **current** and **old** pod IPs of replaced peers:

**Current live pod IPs** (from `kubectl get pods -o wide`):
```
fd00:4:69::c03c    (server)
fd00:4:69:1::d1bd  (server2)
fd00:4:69:2::1358  (server3)
fd00:4:69:3::b094  (node-0)
fd00:4:69:4::d33c  (node-2)
fd00:4:69:5::5a66  (node-1)
```

**Stale pod IPs still present in metrics** (from pre-rollout pods):
```
fd00:4:69:1::4432  (old server2 pod — 1 ping sample, never updated)
fd00:4:69:2::a50a  (old server3 pod — 1 ping sample, 301ms)
fd00:4:69:3::990c  (old node-0 pod — 2 ping samples, never updated)
fd00:4:69:5::fc0f  (old node-1 pod — 1 ping sample, 300ms)
```

Example from the `server` instance's `/metrics`:

```
# Active peer — 32 samples, ~4.7ms avg
goldpinger_peers_response_time_s_sum{call_type="ping",goldpinger_instance="server",host_ip="fd00:4::120",pod_ip="fd00:4:69:1::d1bd"} 0.151
goldpinger_peers_response_time_s_count{...} 32

# Stale peer — 1 sample from rollout, frozen forever
goldpinger_peers_response_time_s_sum{call_type="ping",goldpinger_instance="server",host_ip="fd00:4::120",pod_ip="fd00:4:69:1::4432"} 0.003
goldpinger_peers_response_time_s_count{...} 1
```

The same pattern appears in error counters and UDP metrics:
```
goldpinger_errors_total{goldpinger_instance="server3",type="ping"} 3
goldpinger_udp_errors_total{goldpinger_instance="server3",host="fd00:4:69:3::990c"} 1
```

These errors were caused by briefly pinging a pod mid-termination during the rollout. They're permanent counters that will never reset, and the stale `pod_ip` label means they can't be distinguished from real ongoing failures without cross-referencing the current pod list.

## Impact

- **P95/P99 latency** calculations are inflated because stale single-sample series with rollout-time latency (~300ms) are mixed in with steady-state samples (~5ms)
- **Error rate** metrics include transient rollout errors that never clear
- These artifacts persist until the affected pods themselves restart (i.e. the next rollout), at which point the cycle repeats

## Proposed fix

When goldpinger refreshes its peer list from the Kubernetes API, it should call `DeleteLabelValues()` (or `Delete()`) on the Prometheus metric vectors (`goldpinger_peers_response_time_s`, `goldpinger_errors_total`, `goldpinger_udp_errors_total`, `goldpinger_peers_udp_rtt_s`, etc.) for any `pod_ip` values that are no longer in the current peer set.

This is a common pattern for Go exporters with dynamic label sets — prune metrics for targets that have been removed.

## Environment

- Goldpinger v3.11.0 (Helm chart 1.1.0)
- 6-node kubeadm cluster, IPv6-only pod network (Cilium)
- DaemonSet rolling update strategy (`maxUnavailable=1`)

### PR DESCRIPTION
**Pull request by cooperlees**
When goldpinger refreshes its peer list from the Kubernetes API, it should call DeleteLabelValues() (or Delete()) on the Prometheus metric vectors (goldpinger_peers_response_time_s, goldpinger_errors_total, goldpinger_udp_errors_total, goldpinger_peers_udp_rtt_s, etc.) for any pod_ip values that are no longer in the current peer set.

This is a common pattern for Go exporters with dynamic label sets — prune metrics for targets that have been removed.

Testing:
- Run on test lab k8s cluster and saw problem improve when rolling new versions
- Add testing
  - Even dedicated a commit to table driven subtests mixing IPv4 and IPv6 to ensure we work
  
Fixes #167

### CODE REVIEW

File: pkg/goldpinger/stats.go [hunk 1]
```diff
@@ -300,6 +300,13 @@ func SetPeerHopCount(hostIP, podIP string, hopCount int32) {
 	).Set(float64(hopCount))
 }
 
+// DeletePeerMetrics removes stale metric labels for a destroyed peer.
+// This covers the HTTP ping response-time histogram which is always active.
+// Must be called unconditionally when a peer is removed.
+func DeletePeerMetrics(hostIP, podIP string) {
+	goldpingerResponseTimePeersHistogram.DeleteLabelValues(GoldpingerConfig.Hostname, "ping", hostIP, podIP)
```
Comment (skamboj) [inline pkg/goldpinger/stats.go:308]: Are we missing `goldpingerResponseTimePeersHistogram.DeleteLabelValues(     GoldpingerConfig.Hostname, "check", hostIP, podIP)` here?

Comment (cooperlees) [reply pkg/goldpinger/stats.go:308]: You are right, let's delete them too! My bad.

**Review by skamboj — APPROVED** [review]
LGTM, :shipit:
