### PR TITLE
Fix GOOS problems during simple docker build

### LINKED ISSUE #17: Should set GOOS in build/build.sh
I'm on a mac and I just cut a release of goldpinger, the pod is failing because the exectuable is the wrong format. It's built for Darwin right now. In order to build for the Linux kernel you have to set `GOOS=linux`.

### PR DESCRIPTION
**Pull request by kaduev13**
Fixes #17 

In this PR:
- Added a possibility to pass `GOOS` to `build.sh` (as an environment variable);
- Changed `make build` workflow to:
    - Remove previous binary (the name of binary is hardcoded, because it's also hardcoded in `Dockerfile-simple`);
    - Compile a new binary with `GOOS=linux`;
    - Run docker build.

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -25,7 +26,9 @@ swagger:
 build-multistage:
 	docker build -t $(tag) -f ./Dockerfile .
 
-build: bin/$(bin)
+build:
+	rm -f ./bin/$(bin)
+	$(MAKE) name=${name} version=${version} bin=goldpinger pkg=${pkg} goos=linux && \
```
Comment (seeker89) [inline Makefile]: Hey I'm not sure why change this ? The binary only needs to be rebuilt if any of the `$(files)` is changed, and also this introduces repetition with the `bin/$(bin)` target.

Comment (kaduev13) [reply Makefile]: Thank you for pointing out, to be honest I was not sure about this place.

Actually, I agree with you – just found an approach that is much better 😄(I'm not a pro in `Makefiles`). I'll force-push (and also rebase) the branch.

About the removal of a binary – I thought as we can't gurantee that binary is compiled for the `linux` OS may be it's better to remove it everytime. Otherwise we'll get a broken Docker image. I researched this topic a little bit – looks like it's ok to let the user decide what to do in this case, so I'll remove this part as well 😄

File: build/build.sh [hunk 2]
```diff
@@ -35,6 +35,10 @@ fi
 
 export CGO_ENABLED=0
 export GOARCH="${ARCH}"
+GOOS=${GOOS:-}
```
Comment (seeker89) [inline build/build.sh]: Even if it's just for consistency, I'd recommend

```suggestion
 export GOOS=${GOOS:-}
```

File: Makefile (hunk 1 above)
Comment (seeker89) [reply Makefile]: Great 👍

**Comment by seeker89** [comment]
This looks great. I've just left one cosmetic comment, and then it should be good to go.

Awesome work 👍 !

File: build/build.sh (hunk 2 above)
Comment (kaduev13) [reply build/build.sh]: Yes, thanks, it looks much better! 👍

**Comment by seeker89** [comment]
Hey, sorry for taking over the PR, just wanted to improve the travis file so that we can see that all three ways of building are covered.
